# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issueDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
