# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.IntegerField(default=900)),
                ('category', models.CharField(choices=[(b'FOTODEPILACION', b'Fotodepilaci\xc3\xb3n'), (b'MANICURA', b'Manicura'), (b'PEDICURA', b'Pedicura'), (b'MAQUILLAJE', b'Maquillaje'), (b'TRATAMIENTOS_FACIALES', b'Tratamientos faciales'), (b'TRATAMIENTOS_CORPORALES', b'Tratamientos corporales'), (b'CEJAS_Y_PESTANAS', b'Cejas y pesta\xc3\xb1as')], default=b'FOTODEPILACION', max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
