# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_details', '0003_auto_20170726_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
