# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('second_surname', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=21)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('partner', models.CharField(choices=[('NO_PARTNER', 'No socio'), ('PARTNER_A', 'Tipo A'), ('PARTNER_B', 'Tipo B'), ('PARTNER_C', 'Tipo C')], default='NO_PARTNER', max_length=255)),
                ('partner_release_date', models.DateField(blank=True, null=True)),
                ('known_for', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('INTERNET', 'Internet'), ('RADIO', 'Radio'), ('BOCA_A_BOCA', 'Boca a boca'), ('LOCALIZACION', 'Localizaci\xf3n'), ('PUBLICIDAD_IMPRESA', 'Publicidad impresa'), ('OTROS', 'Otros')], default='FACEBOOK', max_length=255)),
                ('lopd', models.BooleanField(default=False)),
                ('lopd_channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('NONE', 'No LOPD')], default='NONE', max_length=255)),
                ('lopd_options', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FOTODEPILACION', 'Fotodepilaci\xf3n'), ('MANICURA', 'Manicura'), ('PEDICURA', 'Pedicura'), ('MAQUILLAJE', 'Maquillaje'), ('TRATAMIENTOS_FACIALES', 'Tratamientos faciales'), ('TRATAMIENTOS_CORPORALES', 'Tratamientos corporales'), ('CEJAS_Y_PESTANAS', 'Cejas y pesta\xf1as')], default=None, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
