# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='known_for',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('INTERNET', 'Internet'), ('RADIO', 'Radio'), ('BOCA_A_BOCA', 'Boca a boca'), ('LOCALIZACION', 'Localizaci\xf3n'), ('PUBLICIDAD_IMPRESA', 'Publicidad impresa'), ('OTROS', 'Otros')], default='OTROS', max_length=255),
        ),
    ]
