# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170615_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='known_for',
            field=models.CharField(choices=[(b'FACEBOOK', b'Facebook'), (b'INSTAGRAM', b'Instagram'), (b'INTERNET', b'Internet'), (b'RADIO', b'Radio'), (b'BOCA_A_BOCA', b'Boca a boca'), (b'LOCALIZACION', b'Localizaci\xc3\xb3n'), (b'PUBLICIDAD_IMPRESA', b'Publicidad impresa'), (b'OTROS', b'Otros')], default=b'OTROS', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='lopd_options',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'FOTODEPILACION', b'Fotodepilaci\xc3\xb3n'), (b'MANICURA', b'Manicura'), (b'PEDICURA', b'Pedicura'), (b'MAQUILLAJE', b'Maquillaje'), (b'TRATAMIENTOS_FACIALES', b'Tratamientos faciales'), (b'TRATAMIENTOS_CORPORALES', b'Tratamientos corporales'), (b'CEJAS_Y_PESTANAS', b'Cejas y pesta\xc3\xb1as')], default=None, max_length=255, null=True),
        ),
    ]
