# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('CAFETERAPIA', 'Cafeterapia'), ('FITOTERAPIA', 'Fitoterapia'), ('HIALUR\xd3NICO', 'Hialur\xf3nico'), ('LINEA_ESENCIAL', 'L\xednea esencial'), ('LINFODRENANTE', 'Linfodrenante'), ('PERLAS', 'Perlas'), ('PIELES_GRASAS', 'Pieles grasas'), ('PIELES_SENSIBLES', 'Pieles sensibles'), ('METODOS_DE_PAGO', 'M\xe9todos de pago'), ('UNCATEGORIZED', 'Sin categorizar')], default='UNCATEGORIZED', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PrepaidCard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('available_amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2018, 9, 2, 20, 25, 21, 564850, tzinfo=utc))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
            bases=('products.product',),
        ),
    ]
