# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2018, 6, 15)),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(default=datetime.date(2017, 6, 15)),
        ),
    ]
