# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170615_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='prepaidcard',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2018, 6, 15)),
        ),
    ]
