# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170615_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidcard',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 15, 19, 16, 11, 293048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 19, 16, 11, 292317, tzinfo=utc)),
        ),
    ]
