# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 06:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170615_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='prepaidcard',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 30, 6, 28, 8, 947182, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidcard',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 6, 28, 8, 947217, tzinfo=utc)),
        ),
    ]
