# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 19:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170704_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidcard',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='prepaidcard',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 7, 19, 27, 26, 911425, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidcard',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 19, 27, 26, 911394, tzinfo=utc)),
        ),
    ]
