# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 22:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20170707_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidcard',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 22, 54, 16, 617816, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidcard',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 23, 22, 54, 16, 617776, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(b'CAFETERAPIA', b'Cafeterapia'), (b'FITOTERAPIA', b'Fitoterapia'), (b'HIALUR\xc3\x93NICO', b'Hialur\xc3\xb3nico'), (b'LINEA_ESENCIAL', b'L\xc3\xadnea esencial'), (b'LINFODRENANTE', b'Linfodrenante'), (b'PERLAS', b'Perlas'), (b'PIELES_GRASAS', b'Pieles grasas'), (b'PIELES_SENSIBLES', b'Pieles sensibles'), (b'METODOS_DE_PAGO', b'M\xc3\xa9todos de pago'), (b'UNCATEGORIZED', b'Sin categorizar')], default=b'UNCATEGORIZED', max_length=255),
        ),
    ]
