# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 08:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170723_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidcard',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 8, 47, 29, 36178, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidcard',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 8, 47, 29, 36146, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CAFETERAPIA', 'Cafeterapia'), ('FITOTERAPIA', 'Fitoterapia'), ('HIALUR\xd3NICO', 'Hialur\xf3nico'), ('LINEA_ESENCIAL', 'L\xednea esencial'), ('LINFODRENANTE', 'Linfodrenante'), ('PERLAS', 'Perlas'), ('PIELES_GRASAS', 'Pieles grasas'), ('PIELES_SENSIBLES', 'Pieles sensibles'), ('METODOS_DE_PAGO', 'M\xe9todos de pago'), ('UNCATEGORIZED', 'Sin categorizar')], default='UNCATEGORIZED', max_length=255),
        ),
    ]
