# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 08:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20170724_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidcard',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 8, 50, 34, 707328, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidcard',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 8, 50, 34, 707292, tzinfo=utc)),
        ),
    ]
