# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 21:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20170724_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidcard',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 21, 22, 27, 207618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidcard',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 25, 21, 22, 27, 207585, tzinfo=utc)),
        ),
    ]
