# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20170726_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidcard',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 12, 21, 3, 931143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidcard',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 26, 12, 21, 3, 931120, tzinfo=utc)),
        ),
    ]
