# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20170726_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidcard',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 14, 17, 0, 666302, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prepaidcard',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
