# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20170726_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidcard',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 14, 40, 59, 930480, tzinfo=utc)),
        ),
    ]
